# Generated by Django 2.0.2 on 2018-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer_location', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='product_image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
