# Generated by Django 2.0.4 on 2018-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_deliver_date',
            field=models.DateField(default=1970.0, null=True),
        ),
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_deliver_time',
            field=models.TimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
