# Generated by Django 2.0.3 on 2018-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_deliver_date',
            field=models.DateField(default=1970.0, null=True),
        ),
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_deliver_time',
            field=models.TimeField(default='', null=True),
        ),
    ]
