# Generated by Django 2.0.4 on 2018-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20180405_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_note',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
    ]
