# Generated by Django 2.0.2 on 2018-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20180222_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='type_product',
        ),
    ]
