# Generated by Django 2.0.4 on 2018-04-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20180405_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordermodel',
            name='customer_order_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
