# Generated by Django 2.0.4 on 2018-04-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_customerordermodel_customer_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordermodel',
            name='customer_order_name',
        ),
        migrations.AddField(
            model_name='customerordermodel',
            name='customer_product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomePage.Product'),
        ),
    ]
