# Generated by Django 2.0.4 on 2018-04-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_auto_20180409_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerordermodel',
            name='customer_product_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HomePage.Product'),
        ),
    ]
